### ISSUE TITLE
Vulnerability in dicer dependency (via busboy/await-busboy)

### ISSUE THREAD

**Issue by yelworc** [koa-better-modules/joi-router#1]
Hi @3imed-jaberi – first of all, thanks for this fork and your maintenance commitment! :slightly_smiling_face: 

As of a few days ago, `npm audit` is reporting a [vulnerability](https://github.com/advisories/GHSA-wm7h-9275-46v2) in the `dicer` package, which koa-joi-router is using through `busboy`. The actual issue was found and reported quite a while ago, but since busboy is an indirect dependency and `await-busboy` seems unlikely to be updated anytime soon, I'm not sure what the best migration path for koa-joi-router would be. If it's feasible to get rid of the await-busboy layer, maybe switching to [this more actively maintained busboy fork](https://github.com/fastify/busboy) would be an option?

**Comment by 3imed-jaberi** [comment]
Hello @yelworc, thanks! I will take a look 👀 ...

**Comment by 3imed-jaberi** [comment]
@yelworc, solved and published [v10.0.0](https://www.npmjs.com/package/@koa-better-modules/joi-router) 🎉!

**Comment by yelworc** [comment]
Nice, thank you!
