### ISSUE TITLE
Missing types

### ISSUE THREAD

**Issue by mobilites-m** [koa-better-modules/joi-router#3]
Hey, hope you're doing great !

After trying to move from the initial _**koa-joi-router**_ to this project, we ran into this weird issue where TypeScript is not finding any types corresponding to **_koa-better-modules/joi-router_**. 

### Issue
It happened as soon as we replaced :
- The initial koa-joi-router import:  `import Router, { Handler } from "koa-joi-router";`
- By this: `import Router, { Handler } from "koa-joi-router";`

Said error;

> Could not find a declaration file for module '@koa-better-modules/joi-router'. 'C:/Dev/m-backend-workspace/node_modules/@koa-better-modules/joi-router/joi-router.js' implicitly has an 'any' type.
  Try `npm i --save-dev @types/koa-better-modules__joi-router` if it exists or add a new declaration (.d.ts) file containing `declare module '@koa-better-modules/joi-router';`
  
 As per [TypeScript Documentation on @types](https://github.com/DefinitelyTyped/DefinitelyTyped/), the _@koa-better-modules/joi-router_ is indeed not defined in the [Types list](https://github.com/DefinitelyTyped/DefinitelyTyped/tree/master/types).
 
 ### Temporary solution
 A temporary solution would be [adding our own types](https://www.typescriptlang.org/docs/handbook/2/type-declarations.html#your-own-definitions) as recommended by Typescript but it's very unlikely to be the most sustainable solution.

 We would like to know if your team is considering adding the types for TypeScript projects.
 Thanks in advance

**Comment by 3imed-jaberi** [comment]
I'll work on it soony and I will keep you updated when it's done!

**Comment by 3imed-jaberi** [comment]
@mobilites-m, ts types added and published [v10.1.0](https://www.npmjs.com/package/@koa-better-modules/joi-router) 🎉!

**Comment by mobilites-m** [comment]
@3imed-jaberi thank you very much it's working like a charm !
