### ISSUE TITLE
Typescript error - differs from already included file name '/node_modules/@types/Koa/index.d.ts' only in casing

### ISSUE THREAD

**Issue by BryceMehring** [koa-better-modules/joi-router#8]
I'm getting the following error: 

```
TS1149: File name '/node_modules/@types/koa/index.d.ts' differs from already included file name '/node_modules/@types/Koa/index.d.ts' only in casing.

Imported via "Koa" from file '/node_modules/@koa-better-modules/joi-router/joi-router.d.ts' with packageId '@types/koa/index.d.ts@2.13.6'
```

Replacing `Koa` with `koa` in `/node_modules/@koa-better-modules/joi-router/joi-router.d.ts` fixes this error. I have `forceConsistentCasingInFileNames` enabled in my tsconfig.

**Comment by j-waaang** [comment]
We stumbled across the same issue and made a PR https://github.com/koa-better-modules/joi-router/pull/9

**Comment by 3imed-jaberi** [comment]
[v12.0.0](https://www.npmjs.com/package/@koa-better-modules/joi-router) is here!
